name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: $HOME/.local/bin/poetry install -v
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: true

      - name: Run pytest
        run: |
          source .venv/bin/activate
          $HOME/.local/bin/poetry run pytest
  snyk_monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Snyk test
        run: snyk test --org=ie-playground --file=poetry.lock --package-manager=poetry --severity-threshold=critical --project-lifecycle=development
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk monitor
        run: snyk monitor --org=ie-playground --file=poetry.lock --package-manager=poetry --project-lifecycle=development --tags=app=snyk-scm-mapper
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  docker_build:
    runs-on: ubuntu-latest
    needs: [snyk_monitor, pytest]
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: |
            nathanroys1/snyk-scm-mapper:latest
            nathanroys1/snyk-scm-mapper:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Snyk Container Test
        run: snyk container test nathanroys1/snyk-scm-mapper:${{ github.sha }} --platform=${{matrix.platform}} --exclude-base-image-vulns --file=Dockerfile --org=ie-playground --severity-threshold=critical --project-lifecycle=development
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Container Monitor
        run: snyk container monitor nathanroys1/snyk-scm-mapper:${{ github.sha }} --platform=${{matrix.platform}} --file=Dockerfile --org=ie-playground --project-lifecycle=development --tags=gitsha=$GITHUB_SHA,app=snyk-sync
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}